### ISSUE TITLE
qdrant 写入索引有时会遇到 Too many open files 导致写入失败

### ISSUE THREAD

**Issue by web3nomad** [bmrlab/gendam#11]
```
Task failed: FrameCaptionEmbedding, /, status: Internal,
 message: "Service internal error: RocksDB open error: IO error: While open a file for appending: /Users/xddotcom/Library/Application Support/cc.musedam.local/libraries/bb486d877bb41ed213d350bd49b58b6ce57ab56725717ccc1815c99b791ff7ee/qdrant/storage/collections/frame-caption-embedding/0/segments/ba7cbbdf-a5e3-4088-a572-6f27fb94a6fe/payload_index/MANIFEST-000005: Too many open files", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Thu, 14 Mar 2024 11:31:04 GMT", "content-length": "0"} }      

```

在打包的 app 执行的时候更容易出现，dev 环境下还没有遇到，可能和启动的配置有关，官方有个参考文档应该和这个错误相关 https://qdrant.tech/documentation/guides/common-errors/

**Comment by web3nomad** [comment]
kino 的配置, 在 /Users/xddotcom/Library/Application Support/com.kino.Desktop/Kino AI Cache/vector_db/qdrant_config.yaml

```yaml
log_level: INFO
storage:
  storage_path: /Users/xddotcom/Library/Application Support/com.kino.Desktop/Kino AI Cache/vector_db/storage
  snapshots_path: /Users/xddotcom/Library/Application Support/com.kino.Desktop/Kino AI Cache/vector_db/snapshots
  temp_path: null
  on_disk_payload: false
  update_concurrency: null
  wal:
    wal_capacity_mb: 32
    wal_segments_ahead: 0
  node_type: Normal
  performance:
    max_search_threads: 0
    max_optimization_threads: 1
  optimizers:
    deleted_threshold: 0.2
    vacuum_min_vector_number: 1000
    default_segment_number: 0
    max_segment_size_kb: null
    memmap_threshold_kb: null
    indexing_threshold_kb: 20000
    flush_interval_sec: 5
    max_optimization_threads: 1
  hnsw_index:
    m: 16
    ef_construct: 100
    full_scan_threshold_kb: 10000
    max_indexing_threads: 0
    on_disk: false
    payload_m: null
service:
  max_request_size_mb: 32
  max_workers: 0
  host: 0.0.0.0
  grpc_port: 6334
  enable_cors: true
  enable_tls: false
  verify_https_client_certificate: false
cluster:
  enabled: false
  p2p:
    port: 6335
    enable_tls: false
  consensus:
    tick_period_ms: 100
telemetry_disabled: true
tls:
  cert: /Users/xddotcom/Library/Application Support/com.kino.Desktop/Kino AI Cache/vector_db/tls/cert.pem
  key: /Users/xddotcom/Library/Application Support/com.kino.Desktop/Kino AI Cache/vector_db/tls/key.pem
  ca_cert: /Users/xddotcom/Library/Application Support/com.kino.Desktop/Kino AI Cache/vector_db/tls/cacert.pem
  cert_ttl: 3600

```
