### ISSUE TITLE
surrealdb 版本到 2.0.4 会遇到 ort 的 CoreML 依赖报错

### ISSUE THREAD

**Issue by web3nomad** [bmrlab/gendam#96]
```
Undefined symbols for architecture arm64:
"___isPlatformVersionAtLeast", referenced from:
    -[CoreMLExecution predict:outputs:getOutputTensorDataFn:] in libort_sys-856e854189dcb077.rlib[53](model.mm.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

是 surrealdb 到 2.0.4 会有这个问题，应该是加了新功能用了 ort，但我没搜到 ort 的依赖
https://github.com/surrealdb/surrealdb/compare/v2.0.2...v2.0.4

目前先 fix surrealdb 的版本到 2.0.3，如果后面需要升级 surrealdb，要留意这个问题，或者在 `.cargo/config.toml` 加 flag，但是这样要测试下 release build 在其他电脑上运行有没有问题。

```toml
[target.aarch64-apple-darwin]
rustflags = ["-Clink-arg=-fapple-link-rtlib"]

[target.x86_64-apple-darwin]
rustflags = ["-Clink-arg=-fapple-link-rtlib"]
```
